### ISSUE TITLE
Trim Extensions not showing up with Elytra Trims 1.2

### ISSUE THREAD

**Issue by V-lpen** [kikugie/elytra-trims-extensions#1]
I am using both 
[More Armor Trims](https://modrinth.com/mod/more-armor-trims) and
[Flower Adornments](https://modrinth.com/datapack/armor-flower-adornments)

and for some reason, everythign else with Elytra Trims works, but the extensions refuse to load. The texture is a missing texture model when rendered in the smithing table too. 
https://mcpaste.io/9e9b8dbaf861b5a0 Heres my log
I can confirm the resource packs are loaded so im unsure what the issue could be

**Comment by FroZtyFire** [comment]
this is also Happening on Fabric as well

**Comment by kikugie** [comment]
Extensions are not compatible with 1.2 update yet. Fabric warns about it in the logs, idk why quilt doesn't though.

**Comment by V-lpen** [comment]
> 

Oh okay! Thank you, i'll just downgrade since I am not using elytra trinkets

**Comment by kikugie** [comment]
Elytra trinkets are supported on 1.1.10

**Comment by kikugie** [comment]
An update on this: I'm working on another ET update, which would break compatibility again, so I rather delay Extensions update until then
