### ISSUE TITLE
Trim Extensions 1.2.0 does not work with All The Trims

### ISSUE THREAD

**Issue by anticode-403** [kikugie/elytra-trims-extensions#2]
Using 1.20.1 with Fabric 0.15.3.

Trim Extensions just does not work. The only visible resource pack is the Flower Adornments pack and, while using More Armor Trims and Geode+, it isn't working. I would have tested Flower Adornments, but its not updated to 1.20 so it would be a waste of time.

**Comment by kikugie** [comment]
In recent versions of Elytra Trims, those packs are applied automatically. You'll see the trims even without them being selected in the resourcepack menu.

**Comment by anticode-403** [comment]
Well, A: They aren't showing up, that's the problem and B: that should probably be clarified in the readme of the mod.

**Comment by kikugie** [comment]
I can't reproduce your problem with a pure setup (Only Elytra Trims, extensions, Fabric API and More Armor Trims), so I'm gonna ask for more info.

Can you upload the full log to [mclogs](https://mclo.gs/)? I'll see if there are any messages about it or conflicting mods. Also pressing F3+S ingame and sending `elytra-features.png` and `elytra-features.txt` will be helpful.

**Comment by anticode-403** [comment]
Did some more testing, the incompatibility is with Elytra Trims Extensions and All The Trims, my bad. However, seeing as Elytra Trims supports All The Trims, I still think this should be fixed and am leaving the issue open for that reason.

[mclog](https://mclo.gs/YBY2KAG). I'll get the elytra-features data in a few hours if you still need it

**Comment by kikugie** [comment]
Yea, there was an issue with All The Trims. I fixed the issue in 2.0 versions of both mods, try doing it with those.
